[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
log = "0.4.22"
env_logger = "0.11.3"
crossterm = "0.27.0"
windows = { version="0.58.0", features = ["Win32_UI_Input_KeyboardAndMouse"] }